### ISSUE TITLE
Webscrapbook sometimes gets stuck saving data (Firefox)

### ISSUE THREAD

**Issue by ghost** [danny0838/webscrapbook#249] opened 2021-11-09 13:29 UTC
I have seen this bug in couple of Windows10/7 virtual machines that are quite limited performance-wise so that might well be related. (I don't have the extension installed on the host machine currently.) And maybe it's a Firefox bug rather than on the extension.
I have NOT seen this bug in a Ubuntu Linux VM, though. Couldn't reproduce in Chrome, either.
The bug has existed for some time (at least already with Webscrapbook 0.125.2 which is when I started using it). Currently I'm using Firefox 93/94 and it happens with a new installation/profile too.

**The bug:**
Webscrapbook gets often stuck at

_Saving data..._

and seems to never finish saving to disk (I have waited quite long, at least 20 minutes).
It happens both in capture tab or source mode.

Inspecting the extension in Firefox reveals that it seems to get stuck in the '_const newFilename = await new Promise..._' (in capturer.js getAvailableSaveFilename->case "folder":->isFilenameTaken).
Execution goes past the line _browser.downloads.onChanged.addListener(onChanged);_ but not to the return two lines below it.
Sometimes it returns and the extension doesn't get stuck.

If I close the stuck capturer log window, Firefox logs it as an error
"_Promise rejected after context unloaded: Actor 'Conduits' destroyed before query 'RuntimeMessage' was resolved_"
The only file added to Webscrapbook/data folder has apparently similar name as the folder would be and contents of one NUL byte. (I think it always adds it, even when saving works, but deletes then?)

**Comment by danny0838** [comment] 2021-11-09 13:40
What is your version of browser, version of WSB, the page URL you are trying to capture, and the capture options you use?

You can get a full list of options through the export button (be aware that there may be a sensitive data like username and password if you supplied in the options, you can selectively mask them out). Or through `capture as` => `advanced`.

**Comment by niilaT** [comment] 2021-11-09 14:25
Seems to happen randomly with any url and the default settings.
To test it's at least not the settings I'm using, I actually installed fresh Windows 10 in VirtualBox VM yesterday; and 64-bit Firefox and Webscrapbook; then I went to www.example.com and clicked on the Capture tab button, and sometimes it got stuck saving data. Chrome in the same VM didn't get stuck within 30 captures that I tried.
As I said the VM was quite low performance one, I assigned it just 2,5 GB of RAM and one slow CPU core. I haven't tried the extension on a better host machine yet.

**Comment by niilaT** [comment] 2021-11-09 15:29
Ok, nice to hear.
FYI I just tested the previous extension also on a faster machine and it was much harder to reproduce there.
But out of like 50-100 tries it did get stuck once (on the example.com site).
I guess the delay you mentioned might be worse in a slow VM.

Also, it failed three times with 
"Fatal error: Promised response from onMessage listener went out of scope"
error in the capturer window (after Saving data...), though I don't remember seeing that earlier.

**Comment by danny0838** [comment] 2021-11-09 15:30
Can you confirm that whether the issue is resolved in 0.138.0?

**Comment by niilaT** [comment] 2021-11-09 16:47
Yes, seems to be working reliably now :+1:

**Comment by danny0838** [comment] 2021-11-09 16:48
Close issue. Thank you for following up.

**Comment by GHolk** [comment] 2022-12-06 06:04
Hey, this still happen randomly in 1.5.1, firefox 107.0.1 on windows rarely.

**Comment by danny0838** [comment] 2022-12-07 13:29
@GHolk Thank you for the report but unfortunately we cannot do further investigation if it happens so rarely and no clear steps to reproduce.

Please provide the source URL of the page to be capture, the log of the capture dialog, the capture options, and the version of the browser and WebScrapBook if it happens again.

Also check if there is another browser extensions that provides downloading functionality, which may interfere with WebScrapBook, and try if disabling it makes a difference.

**Comment by GHolk** [comment] 2022-12-22 10:01
I hive some `console.log` code, and suspect that the
`browser.downloads.removeFile()` in `isFilenameTaken` does not resolve sometimes
(and does not reject too).
Then, I set a timeout for removeFile and retry it, and the bug does not occur,
thought I am not very confident on their relationship.

**Comment by danny0838** [comment] 2022-12-26 13:20
@GHolk Thank you for the information.

Do you confirm whether there is another browser extension that involves downloading functionality? This is a possible cause of an unresponsive downloading.

**Comment by danny0838** [comment] 2022-12-26 15:16
Implemented a fix in 1.5.3 that should error out rather than hang forever if an unexpected error occurs during handling the downloading. This does not resolve the root cause of the error, however.

**Comment by GHolk** [comment] 2022-12-28 07:32
Hey, I tried and got the following error two times:

```
Fatal error: Failed to download "WebScrapBook/data/20221228072244160-也談捷運路網圖 – contingent thoughts":
Could not remove download id 7 because the file doesn't exist
```

But the file does exist when I check the folder after the message show up.

I believe this is the reason for the issue I mentioned.

I was wrong about the `browser.downlaods.remove` did not reject.
It did reject but did not get caught.

**Comment by danny0838** [comment] 2022-12-28 13:04
@GHolk Thank you for the information. This seems to a bug of Firefox, and we have raised an [issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1807815) to the developers.

**Comment by GHolk** [comment] 2023-01-03 03:37
Hey, would you like to accept PR to fix this in extension level?
I does not think mozilla will fix this bug very quickly.

**Comment by danny0838** [comment] 2023-01-03 12:38
PR is welcome. But I wonder if there's a reliably to fix this.

**Comment by GHolk** [comment] 2023-02-04 09:32
Hey, I think my commits  855e766...51efc0d44805ba828acb5281d70192e55c0a8429 can mostly fix this issue.

**Comment by danny0838** [comment] 2023-02-10 13:31
We have found multiple issues that may happen for concurrent captures to local folder, which should have been mostly fixed in 1.8.0

**Comment by danny0838** [comment] 2023-04-13 14:31
@GHolk Can you confirm whether the issue is still reproduced in WSB >= 1.8.0?

**Comment by GHolk** [comment] 2023-04-15 08:43
I have not encounter this for a while.
I think we could close this issue.
If anyone encounter this, they will re-open it.

**Comment by danny0838** [comment] 2023-04-15 08:58
Thank you for the feedback.

**Closed by danny0838** 2023-04-15 08:58 UTC
Labels: bug
