### ISSUE TITLE
how to capture this page

### ISSUE THREAD

**Issue by grotesque** [danny0838/webscrapbook#329] opened 2023-01-27 15:02 UTC
https://www.dietdoctor.com/why-youre-not-in-ketosis

The capture just hangs for me.

**Comment by danny0838** [comment] 2023-01-27 16:20
What is the message in the log?

**Comment by danny0838** [comment] 2023-01-29 13:56
Due to lack of further information. We'll treat this as a duplicate of #330

**Closed by danny0838** 2023-01-29 13:56 UTC
