### ISSUE TITLE
Item not positioned correctly when moved into another item through drag-and-drop 

### ISSUE THREAD

**Issue by hjohanns** [danny0838/webscrapbook#265] opened 2022-02-04 08:24 UTC
We are starting to use WebScrapBook and PyWebScrapBook in the team.
After an initial period, we see events happening, where some folders disappear from the tree.
When studying the meta.js and toc.js files, the folders are there, but in the toc.js nobody references them.
Could there be a problem writing down the toc.js, or could they become corrupted for some reason in the plugin?
The backend server log shows a normal traffic of GET and POST with documents, and with the meta.js and toc.js.
There are multiple users on the system, but I see that the client takes a lock before posting files.
Is there any way we could collect more information about what is happening?
Thank you so much, hubert j.

**Comment by danny0838** [comment] 2022-02-15 22:40
Implemented a tentative fix. Please check if this issue still happens in 1.3.0.

**Comment by danny0838** [comment] 2022-02-19 09:27
We have found the root cause.

Say there is a tree like this:

```
FolderX
  ItemA
  ItemB
ItemC
```

When dragging ItemC into FolderX, the desired result is to insert ItemC at the bottom of FolderX, i.e.:

```
FolderX
  ItemA
  ItemB
  ItemC
```

However, due to some issue in the code of version 1.2.0, the actual TOC is that ItemC be inserted at the top of FolderX, i.e.:

```
FolderX
  ItemC
  ItemA
  ItemB
```

, while the GUI still shows as the former.

If the user then attempts to move ItemC to somewhere, it will be interpreted as "remove the last item (which is actually ItemB) from FolderX, and then insert ItemC at somewhere", and thus the user will see duplicated ItemC and find that ItemB is missing.

In 1.3.0 we have made a tentative fix to rebuild the GUI tree after TOC has been updated, and thus ItemC is moved to the top of FolderX when dragged into FolderX.

In 1.3.1 we have fixed the issue and ItemC is correctly moved to the bottom of FolderX when dragged into FolderX.

**Closed** 2022-03-11 11:01 UTC
Labels: bug
