### ISSUE TITLE
Error: missing task data for mission "..." when invoking a capture from the context menu of a Firefox private window.

### ISSUE THREAD

**Issue by qdinar** [danny0838/webscrapbook#266] opened 2022-02-14 07:49 UTC
" Error: missing task data for mission "39ea4cbf-c816-46c9-ad5c-7aba777d82b4". " while saving https://www.azatliq.org/a/31699594.html .

**Comment by danny0838** [comment] 2022-02-14 08:44
I cannot reproduce the issue. Does it always happen when you perform the capture?

This is normal if the dialog has been refreshed, which is intended to prevent accidentally performing a capture again, which might corrupt the data.

**Comment by qdinar** [comment] 2022-02-14 09:51
it happen when i open it in a private window, always. in normal window, i have noscript addon active and some scripts disabled, and the page is saved, probably for that (missing scripts). ff 97.0, wsb 1.2.0 .

**Comment by qdinar** [comment] 2022-02-14 09:58
i tried to enable all script domains on the page in the normal window, and i see that wsb works.

**Comment by danny0838** [comment] 2022-02-15 06:44
Not sure if I get you. Does it work in a private window after you did the tweaks?

**Comment by qdinar** [comment] 2022-02-15 07:34
noscript is disabled for private windows, and all script domains are enabled in them. so, i cannot not change that in private windows. i do not think that changes effected them in any way. now, i tried it one more time, and all scripts are enabled for normal windows, and it still does not work in private window.

**Comment by qdinar** [comment] 2022-02-15 07:43
so, the problem is probably not with scripts, but maybe with some addons. i have these enabled for private windows: ContextSearch web-ext, Link Status Redux, WebScrapBook.

**Comment by qdinar** [comment] 2022-02-15 07:50
i tried to disable that 2 other addons for private windows, only wsb is left, tried to save, and the error still appears.

**Comment by qdinar** [comment] 2022-02-15 07:58
now, i tried to install wsb to an almost fresh profile, that was prepared for such cases, to test, so, there was only 1 addon, wsb, and it worked in normal window and there was same message in private window.

btw i checked and i saw that the code in quotes in error message changes with every try of saving.

**Comment by qdinar** [comment] 2022-02-15 08:01
similar message appears for https://vk.com/qdinar in private window.

**Comment by qdinar** [comment] 2022-02-15 08:04
similar message is even with http://example.com/ , which is a quite simple page.

**Comment by danny0838** [comment] 2022-02-15 22:39
This should happen only when the capture is invoked from the context menu of a Firefox private window, due to some issues of the internal storage handling. This should be fixed in 1.3.0.

**Closed** 2022-02-19 09:29 UTC
Labels: bug
