### ISSUE TITLE
Capture doesn't response

### ISSUE THREAD

**Issue by Urvieh** [danny0838/webscrapbook#31] opened 2017-11-26 00:20 UTC
I cannot even save bookmarks. There is definitely activity, the "busy" cursor shows for half a second or so, but that is it.

**Comment by danny0838** [comment] 2017-11-26 04:39
Please provide more detail: What is your version of OS, browser, Web ScrapBook? What are the steps you do? On which web page? Are you in a private/incognito mode?

**Comment by Urvieh** [comment] 2017-11-26 09:07
Firefox 57.0, 64bit Windows 10 Pro.
No private mode.
All websites.
I right-click and choose either Capture, Capture (source) or Capture (bookmark), or I do it from the icon in the menu. I restarted the computer, and I closed all applications other than Firefox.

**Comment by cy7yz2rj** [comment] 2017-11-26 12:19
I think this happened to me as well, it had to do with the default download location.

Try this:
1. about:preferences  > choose "Always ask where to save files"
2. Capture page, Firefox should pop a dialogue box asking what to do with the output
3. Tick remember this choice and save
4. about:preferences > restore your original setting

Now when you capture a page, it should automatically be saved to your chosen download folder.

**Comment by Urvieh** [comment] 2017-11-26 12:26
Thanks for your reply. I had tried this already. It changed nothing.

**Comment by cy7yz2rj** [comment] 2017-11-26 12:40
You're right, I think something is broken in the last update(s). I just made a new profile for testing and can't get WS to work at all.

**Comment by Urvieh** [comment] 2017-11-26 12:49
I had an old (MozBackup) copy with the previous version of WebScrapbook. I restored it and everything is fine on most sites.

**Comment by danny0838** [comment] 2017-11-26 12:56
@Urvieh which is the WebScrapbook that worked fine?

Could you try using latest version of Web ScrapBook with a new Firefox user profile and without any addon other than Web ScrapBook?

**Comment by cy7yz2rj** [comment] 2017-11-26 13:23
This is odd, on a fresh profile of 57.0 (64-bit) in Debian GNU/Linux it never works yet it sort of does on a fresh Nightly 59.0a1 (2017-11-26) (64-bit) profile but it's still very hit-and-miss, sometimes it saves a page, sometimes it doesn't.

**Comment by danny0838** [comment] 2017-11-26 13:35
Please check whether there is a small red number shown at the Web ScrapBook toolbar button when you find the capture fail. Sometimes you just have to wait for a while for the popup to prompt. Also make a test with the "save in ScrapBook folder" option checked or capture the same web page with same options in Chrome.

Firefox has unfixed bugs causing the GUI not work as it ought to. We've spent a lot of time finding a workaround that could at least work, but it might still cause issues. We need to make sure whether it's caused by the workaround or there is a reason causing the web page not capturable.

**Comment by cy7yz2rj** [comment] 2017-11-26 13:49
There was never a red number that I could spot, the only visible indication I had that WS was doing something was in the tab bar, what appears to be a new tab opening flashes very briefly, both when captures fail and succeed.

Saving in ScrapBook folder does appear to work consistently, on Firefox 57 fresh profile.

**Comment by Urvieh** [comment] 2017-11-26 15:05
It has stopped working again. No red number. It started off doing nothing here:

https://www.rt.com/news/410923-norway-f35-sensitive-data-us/

**Comment by cy7yz2rj** [comment] 2017-11-26 15:24
Did you toggle the **Save captured data in ScrapBook** option in about:addons > Web ScrapBook > Preferences (don't forget to click Save at the bottom of the page before exiting)?
Turning it on made everything work again for me, at the expense of captures being saved inside a Scrapbook folder tree instead of the root of the chosen download location.

The number of concurrent Firefox processes is set by `dom.ipc.processCount` in about:config, or in about:preferences > General > Performance. It is a native Firefox feature, unrelated to WS.

**Comment by Urvieh** [comment] 2017-11-26 15:36
Yes, I did, and thank you for the information on the processes.

**Comment by cy7yz2rj** [comment] 2017-11-26 15:50
Tested your URL with the FF57 fresh profile, for me it still works when saving to scrapbook folder though not every time, sometimes it fails. Not saving to scrapbook folder never works, still.

**Comment by Urvieh** [comment] 2017-11-26 17:20
Okay: Safe data to WebScrapbook is working now. I could live with it if I got a save-as dialogue. I would then be able to choose the folders according to topics as I would normally do.

**Comment by danny0838** [comment] 2017-11-26 20:02
We did some change in 0.20.0 which may fix this issue.

**Comment by cy7yz2rj** [comment] 2017-11-26 20:23
Seems fixed on my end, so far all attempts at capturing were successful, both to scrapbook folder and not.

**Comment by Urvieh** [comment] 2017-11-26 21:08
0.20 works fine. Is there a way to avoid the pop-up window? BTW, it also appears in the history.

**Comment by danny0838** [comment] 2017-11-27 01:38
@Urvieh Could you provide a reason why you'd like the popup not appear? We probably are not going to remove it since it provides a better real-time feedback, a better log and error report, and a better control, and there are some unresolvable issues for a pure background capture.

**Comment by danny0838** [comment] 2017-11-27 02:02
It seems that only Firefox generates a history entry for the popup window. We can suppress it, but it requires an additional permission.

**Comment by danny0838** [comment] 2017-11-27 14:17
Implemented history suppress in 0.21.0, which requires a new permission "history" (and unfortunately, this isn't supported on Firefox Android).

Also implemented another way for the download prompt to support older Firefox version, this is more "natural" and should be less likely to cause an issue, but some observation is probably  still need .

**Comment by alensen** [comment] 2017-11-27 14:26
I tested the new version of web scrapbook with Vivaldi 1.13 on Linux Mint 18.2, but got following error message when i tried to capture a tab:

Capturing (document) [27] https://www.alphagalileo.org/ViewItem.aspx?ItemId=181129&CultureCode=en ...
Fatal error: Cannot read property 'forEach' of null

see also attached screenshot. It happens with all different websites that i have tried.

![bildschirmfoto_2017-11-27_15-24-39](https://user-images.githubusercontent.com/34032277/33271290-1fec448e-d387-11e7-874e-056e7c237756.png)

**Comment by danny0838** [comment] 2017-11-27 14:44
@alensen The issue happens in `capturer/capturer.js:143`, because **chrome.webNavigation.getAllFrames returns null for a tabId of an existed tab**, while it should return an array of frames. It seems to be a bug for Vivaldi. You can report it to the official support.

**Closed** 2017-12-04 05:59 UTC
Labels: bug
