### ISSUE TITLE
Is it possible to scrape as background work?

### ISSUE THREAD

**Issue by acowdont** [danny0838/webscrapbook#209] opened 2021-03-15 10:46 UTC
If the capture window is not focused, the capturing operation will not proceed. When making multiple scraping, I have to focus the windows one by one. What codes do I need to modify to make it work in the background?

Thanks

**Comment by danny0838** [comment] 2021-03-15 23:44
This issue is a duplicate of #191 and we'll trace it there.


Although it's technically possible to run the capture in the background, there are still many issues preventing it, and the code has to be largely refactored to support it.


According to our tests in both Firefox and Chrome, captures in non-active windows will eventually finish, so you probably don't need to focus them one by one, though the browser may somehow slow down their execution.


It's less encouraged to run multiple captures in the same time, as they would block each other when uploading to the backend server. To capture multiple pages you can select multiple tabs and run a batch capture task to capture them one by one in a queue.

**Closed by danny0838** 2021-03-15 23:44 UTC
