### ISSUE TITLE
suggest: rename metadata context menu item; add dialog on "new folder"

### ISSUE THREAD

**Issue by pbpb** [danny0838/webscrapbook#312] opened 2022-12-24 22:41 UTC
Hiya.

New user.  It took me 5 minutes to figure out that the way to rename a new folder from "new folder" to something else was to use the new folder's context menu item "metadata."  It would have been helpful to me if this instead were called "metadata for this folder" or "Folder Metadata" or even better maybe for naive users "Folder Properties" (which is what I think legacy scrapbook had).

In addition, most people probably do not want their new folder to be called "new folder" so it would be useful if the "new folder" pulldown menu feature immediately presented an option dialog to name the folder before creating it, prefilled to "new folder" so if you just hit return you get the current behavior.

Maybe this is already enabled somehow, but I do not see it.  I am just squawking as I come across these as a new user, in the hopes that this creates easier adoption for others.

Thanks.  I'm sure you will be rewarded in the next life for creating this extension.

**Comment by danny0838** [comment] 2022-12-26 11:32
Duplicate of #278

**Closed** 2022-12-26 11:33 UTC
Labels: duplicate
