### ISSUE TITLE
Import data from old scrapbook folder

### ISSUE THREAD

**Issue by strannick-ru** [danny0838/webscrapbook#23] opened 2017-11-20 18:34 UTC
Hello.
I have old (really old) folders with Scrapbook data.

May I import it to webscrapbook?

**Comment by RvdGijp** [comment] 2017-11-21 08:38
We have the same problem!

**Comment by danny0838** [comment] 2017-11-21 12:01
Duplicate of #14. Use built-in site indexer for full index build up and [ScrapBook X File Converter](https://addons.mozilla.org/firefox/addon/scrapbookx-converter/) to convert to other archive formats.

**Closed by danny0838** 2017-11-21 12:01 UTC
