### ISSUE TITLE
Implement the spider mode ("In-depth Save" known in old Scrapbook)

### ISSUE THREAD

**Issue by kantrol** [danny0838/webscrapbook#130] opened 2019-12-29 12:54 UTC
can we follow the contained links and download those pages (with filters) to a certain depth?

**Comment by danny0838** [comment] 2019-12-31 11:49
Duplicate of #95.

This feature is in our to-do list but the implementation requires a very large code rework and is thus still pending.

**Closed** 2019-12-31 11:49 UTC
Labels: duplicate
