### ISSUE TITLE
Location of target Save directory

### ISSUE THREAD

**Issue by Len44** [danny0838/webscrapbook#67] opened 2018-06-17 17:44 UTC
QUESTION: Where is the page saved? In the Options, I set it to a folder in my Documents folder (Windows 10) but nothing is there.

**Comment by danny0838** [comment] 2018-06-18 06:52
As the tooltip (see figure below) says, the specified directory must be under the download directory. This issue is a duplicate of #17 and visit there for details.

![default](https://user-images.githubusercontent.com/531417/41521993-e303e9ee-7306-11e8-8286-83b3805c6b59.png)

**Closed by danny0838** 2018-06-18 06:52 UTC
