### ISSUE TITLE
Reddit.com  can't not saved

### ISSUE THREAD

**Issue by brain8891** [danny0838/webscrapbook#70] opened 2018-07-05 09:55 UTC
Reddit.com can't save any page

**Comment by danny0838** [comment] 2019-03-08 12:31
We cannot reproduce thia issue as a page under reddit.com can be saved. Though, we found that there's some issues about the stylesheets, which is a similar but different issue. Can you confirm which is the exact issue you met?

**Comment by danny0838** [comment] 2019-04-24 16:18
Close this issue since no further clarification and a more specific issue is available as #109.

**Closed by danny0838** 2019-04-24 16:18 UTC
Labels: bug
