### ISSUE TITLE
Page captured from The Washington Post shows altered chars

### ISSUE THREAD

**Issue by sj365** [danny0838/webscrapbook#131] opened 2020-01-04 15:02 UTC
The current version of Webscrapbook is not saving pages with apostrophes correctly.

https://www.washingtonpost.com/weather/2020/01/02/mild-wet-december-concludes-third-warmest-year-record-washington/

[Mild and wet December concludes third-warmest year on record in Washington - The Washington Post.zip](https://github.com/danny0838/webscrapbook/files/4022047/Mild.and.wet.December.concludes.third-warmest.year.on.record.in.Washington.-.The.Washington.Post.zip)

Rename zip to html and look for any words that contain apostrophes and you will see the distorted characters
1.On the right side of page under heading Most Read Local 1. TS Elliot section
2. On the right side of page under Post Reports Latest Episode heading is messed up
3.On the right side of page under At a Glance see the temperatures with altered symbols

Windows 10
Firefox 71, Chrome 79, Opera 65

**Comment by danny0838** [comment] 2020-01-05 03:19
The "Most Read Local" part of the web page seems to be changing over time and I cannot find what exactly the problem you are mentioning. Could you provide a screenshot for illustration?

**Comment by sj365** [comment] 2020-03-04 19:39
Hello, 
I was in my last semester towards completing my university degree so sorry for the delayed response.    Using https://www.washingtonpost.com/weather/2020/01/02/mild-wet-december-concludes-third-warmest-year-record-washington/   and saving with wsb produced a page that would show altered characters if opened with chrome browser.  Opened with Firefox would not produce the same effect.  This can be duplicated if you rename the previously sent zip to html and open with recent chrome browser.  Opened with recent Firefox browser will not show the same.  Attached are the requested screenshots to demonstrate the issue.
[wsb ss apostrophe.zip](https://github.com/danny0838/webscrapbook/files/4289359/wsb.ss.apostrophe.zip)

However, I just did a retest with the current wsb and saved the same wpost link and the artifacts do not appear any longer so the issue may be resolved allready.

**Comment by danny0838** [comment] 2020-03-05 05:42
Thank you for further information. What was the browser and version you used to capture the page at the first time?

**Comment by sj365** [comment] 2020-03-06 16:10
the browser info was
Windows 10
Firefox 71, Chrome 79, Opera 65

If there was a WSB update between January and now it likely fixed the isssue.  I cant test further now because neither WSB Firefox or Chrome .html / .maff is saving nytimes or thewashingtonpost.  Other sites wsj.com, cnet.com are saving.

**Comment by danny0838** [comment] 2020-05-04 07:16
@sj365 The issue of failing to capture a page in those sites should be fixed in the latest version. Can you confirm whether this issue still persists?

**Comment by danny0838** [comment] 2020-11-13 15:17
Close stale issue due to lack of further information, and seems possibly resolved already as we cannot be reproduce it currently.

**Closed by danny0838** 2020-11-13 15:17 UTC
Labels: help wanted
