### ISSUE TITLE
Autosave issues

### ISSUE THREAD

**Issue by yellowslug** [danny0838/webscrapbook#215] opened 2021-05-02 17:16 UTC
Thank you for adding AutoCapture(AC) as an option to WebScrapBook (WSB)! I am having issues configuring it.

1. Is there a simple way to tell AS not to save pages? The only thing that works for me is to set delay to a huge value. There will be very many of these (banks, mail, apps, ...). Won't all these timers place a load on system resources? 
```
 	{
    	"name": "WSB.AC.ignore",
    	"pattern": "/.*economist.com.*/i",
    	"delay": 10000000
   	}
```

2. The following configuration is never applied to any pattern.
 ```
         {
    	"name": "WSB.AC.always",
    	"pattern": [ "/.*economist.com.*/i", "/.*stockcharts.com.*/i" ],
    	"delay": 2000
   	}
```

3. The following configuration is only applied to the last pattern listed
```
          {
    	"name": "WSB.AC.always",
    	"pattern": "/.*economist.com.*/i",
        "pattern": "/.*stockcharts.com.*/i" ],
    	"delay": 2000
   	}
```

4. i do not understand multiple configurations. In the example below the default configuration is applied.  This happens whether the default configuration is first or last in the array.
```
[
    	{
    	"name": "WSB.AC.default",
    	"delay": 10000
   	},
 	{
    	"name": "WSB.AC.ignore",
    	"pattern": "/.*economist.com.*/i",
    	"delay": 30000
   	}
]
```

5. In the following matrix, which of the configurations will trigger?
```
 [
  	 {
    	"name": "WSB.AC.ignore",
    	"pattern": "/.*econoday.com.*/i",
    	"delay": 30000
   	},
       {
    	"name": "WSB.AC.always",
	"allowDuplicate": 1,
    	"pattern": ["/.*us.econoday.com.byshoweventfull.*/i",
    	"delay": 2000
   	}
]
```

**Comment by danny0838** [comment] 2021-05-03 18:00
@yellowslug 
> 1. Is there a simple way to tell AS not to save pages? The only thing that works for me is to set delay to a huge value. There will be very many of these (banks, mail, apps, ...). Won't all these timers place a load on system resources?

Not to save what pages?

If you want to disable autocapture, just uncheck the checkbox of `Enable auto-capture`, and this will immediately terminate all pending autocaptures.

If you want to disable a specific rule, just add a `"disabled": true` key-value pair to that rule.

If you want something like setting a rule that works for any site except for a specific one, you'd have to learn some advanced RegExp syntax like:

    {
      "description": "Capture any site except for http://example.com",
      "pattern": "/^(?!http://example\\.com)/i",
      "delay": 1000
    }

> 
> 2. The following configuration is never applied to any pattern.
> 
> 
> ```
> {
>   "name": "WSB.AC.always",
>   "pattern": [ "/.*economist.com.*/i", "/.*stockcharts.com.*/i" ],
>   "delay": 2000
> }
> ```

As the tooltip says, the `pattern` only accepts a string, and passing an array is invalid, and will eventually cause a script error when the rule is checked against, causing the rule be skipped.

You can just set a rule for each site:

    [
      {
        "name": "Capture economist",
        "pattern": "/.*economist.com.*/i",
        "delay": 2000
      },
      {
        "name": "Capture stockcharts",
        "pattern": "/.*stockcharts.com.*/i",
        "delay": 2000
      }
    ]

> 
> 3. The following configuration is only applied to the last pattern listed
> 
> 
> ```
>  {
>   "name": "WSB.AC.always",
>   "pattern": "/.*economist.com.*/i",
>   "pattern": "/.*stockcharts.com.*/i" ],
>   "delay": 2000
> }
> ```

For JSON, the behavior of an object with duplicated keys is undefined and may vary among different implementations, and most browsers would take only the last instance.

If you want to set multiple rules, do as mentioned in point 2.

> 
> 4. i do not understand multiple configurations. In the example below the default configuration is applied.  This happens whether the default configuration is first or last in the array.
> 
> 
> ```
> [
>   {
>     "name": "WSB.AC.default",
>     "delay": 10000
>   },
>   {
>     "name": "WSB.AC.ignore",
>     "pattern": "/.*economist.com.*/i",
>     "delay": 30000
>   }
> ]
> ```

All rules should work independently. In your example, if you visit a page at economist.com, a capture will happen 10 seconds after the page is loaded, and another capture will happen 30 seconds after the page is loaded.

However, as "allowDuplicate" is not set for the second rule, the second auto-capture will detect a duplicate and skip the capture, unless the first auto-capture has not succeeded due to some issue.

> 
> 5. In the following matrix, which of the configurations will trigger?
> 
> 
> ```
>  [
>   	 {
>     	"name": "WSB.AC.ignore",
>     	"pattern": "/.*econoday.com.*/i",
>     	"delay": 30000
>    	},
>        {
>     	"name": "WSB.AC.always",
> 	"allowDuplicate": 1,
>     	"pattern": ["/.*us.econoday.com.byshoweventfull.*/i",
>     	"delay": 2000
>    	}
> ]
> ```

As mentioned in 4., both rules should work. But the second rule is invalid as mentioned in 2., and thus it will actually never trigger.

Additionally, setting a RegExp string like `"/.*economist.com.*/i"` is flawed—this will trigger a capture for something like `http://fakeconomisticom.us` or `http://any.site/data/economist.com`. If you intended to capture only a page at optionally a subdomain of `economist.com` under optionally a top domain like `.en`, you probably should write a RegExp string like `"^/https?://(?:\\w+\\.)?economist\\.com(?:\\.\\w+)?/i"`. If you are not familiar with RegExp, just search for a documentation to learn from.

**Comment by yellowslug** [comment] 2021-05-05 07:09
Assume i want to capture any page, except economist.com, that is visited for more than 2 minutes. The config for this might be written as follows
```
[
    	{
        "pattern": "^/.*economist.com.*/i",
    	"delay": 120000
   	}
]
```
Now assume i want to exclude both economist.com and stockcharts.com. This requires a second config which might result in the following
```
[
    	{
        "pattern": "^/.*economist.com.*/i",
    	"delay": 120000
   	},
    	{
        "pattern": "^/.*stockcharts.com.*/i",
    	"delay": 120000
   	}
]
```
Since each config only allows one pattern and all configs are evaluated isn't it impossible to exclude more than one website? Yes, it is possible to combine both patterns into a single regular expression
```
[
     {
       "pattern:": "^/(.*economist.com.*|.*stockcharts.com.*)/i",
    	"delay": 120000
     {
]
```
but there will be very many exceptions. Won't the RegEx exceed some maximum length or complexity at some point?

i propose adding matrix support to the pattern definition and terminating processing when the first config is executed. Is this possible?

Please.

**Comment by danny0838** [comment] 2021-05-05 09:14
> Assume i want to capture any page, except economist.com, that is visited for more than 2 minutes. The config for this might be written as follows
> 
> ```
> [
>     	{
>         "pattern": "^/.*economist.com.*/i",
>     	"delay": 120000
>    	}
> ]
> ```

`"^/.*economist.com.*/i"` is invalid. You should follow what I mentioned in prior and use something like `"/^(?!http://example\\.com/)/i"`.

> 
> Now assume i want to exclude both economist.com and stockcharts.com. This requires a second config which might result in the following
> 
> ```
> [
>     	{
>         "pattern": "^/.*economist.com.*/i",
>     	"delay": 120000
>    	},
>     	{
>         "pattern": "^/.*stockcharts.com.*/i",
>     	"delay": 120000
>    	}
> ]
> ```

This won't work as you expected. Each config works independently and you can never add an exclude pattern for a config through another config.

> 
> Since each config only allows one pattern and all configs are evaluated isn't it impossible to exclude more than one website? Yes, it is possible to combine both patterns into a single regular expression
> 
> ```
> [
>      {
>        "pattern:": "^/(.*economist.com.*|.*stockcharts.com.*)/i",
>     	"delay": 120000
>      {
> ]
> ```
> 
> but there will be very many exceptions. Won't the RegEx exceed some maximum length or complexity at some point?

This is also invalid for the same reason.

I don't think it's a good habit to create lots of configs that runs for "all sites except for xxx, yyy, zzz, ...". Set each rule that runs for 1 or 2 specific sites is probably more likely a reasonable general case.

A RegExp pattern can be as large as several MBs, which is probably large enough for general usage. Separating into multiple include and exclude RegExps may be possible but won't benefit too much, and could decrease the performance as testing against multiple RegExps may be slower than testing against one large RegExp as setting up each RegExp has its internal overhead.

> 
> i propose adding matrix support to the pattern definition and terminating processing when the first config is executed. Is this possible?
> 
I don't get what " adding matrix support to the pattern definition and terminating processing when the first config is executed" actually means. Please be more specific and descriptive.

**Comment by yellowslug** [comment] 2021-05-05 22:40
Sorry, i meant to say array support, not matrix support... my bad.

The exact RegExp patterns to use are not necessary for this conversation.   `.*economist.com.* `is just more readable.

My initial attempt to configure AC listed 26 domains to ignore. Something like
```
[
{
"pattern": [ "/.*domain1.*/", "/.*domain2.*/", ... "/.*domain26.*/" ],
"ignore:", 1
}
]
```
Many more will be added before AC is fully configured.

i've tried complex regular expressions much shorter than the one  i will need to ignore a long list of domains. They did not always compile and did not always work on different machines. A lot depends on the RegExp library.

Regards,

**Comment by yellowslug** [comment] 2021-05-05 22:45
Sorry again... 

by terminating processing i meant evaluate multiple configurations sequentially each time a page is loaded and stop after processing the first matching configuration

**Comment by danny0838** [comment] 2021-05-06 08:56
> by terminating processing i meant evaluate multiple configurations sequentially each time a page is loaded and stop after processing the first matching configuration

Can you provide some real use cases? I wonder there's a case that cannot be handled by creating a single config with an appropriate RegExp rule...

The current syntax is made similar to capture helpers. Although it's not unchangeable. We would avoid making a breaking change unless there's enough benefit and good justification.

> i've tried complex regular expressions much shorter than the one i will need to ignore a long list of domains. They did not always compile and did not always work on different machines. A lot depends on the RegExp library.

I don't think this is a valid reason. The only reason that a RegExp doesn't compile is incorrect syntax. What you need is to correct the syntax; otherwise separating them into multiple smaller RegExps won't fix it at all. In addition, JavaScript RegExp flavor is one that supports the least features, and it's very unlikely that a JavaScript parsable RegExp cannot be supported by another flavor.

**Comment by yellowslug** [comment] 2021-05-06 19:18
Hi Danny...

Here is an example of a real use case defined as i propose. The only change is that i anonymized the WSB.AC.ignore domains.
```
[
   	{
    	"name": "WSB.AC.always",
	"allowDuplicate": 1,
    	"pattern": [ "/.*us.econoday.com.byshoweventfull.*/i", "/.*cnbc.com.202.*/i" ],
    	"delay": 2000
   	},
   	{
    	"name": "WSB.AC.ignore",
		"ignore": 1,
    	"pattern": [
			"/.*domain01.*/i", "/.*domain02.*/i", "/.*domain03.*/i",
			"/.*domain04.*/i", "/.*domain05.*/i", "/.*domain06.*/i",
			"/.*domain07.*/i", "/.*domain08.*/i", "/.*domain09.*/i",
			"/.*domain10.*/i", "/.*domain11.*/i", "/.*domain12.*/i",
			"/.*domain13.*/i", "/.*domain14.*/i", "/.*domain15.*/i",
			"/.*domain16.*/i", "/.*domain17.*/i", "/.*domain18.*/i",
			"/.*domain19.*/i", "/.*domain20.*/i", "/.*domain21.*/i",
			"/.*domain22.*/i", "/.*domain23.*/i", "/.*domain24.*/i",
			"/.*domain25.*/i", "/.*domain26.*/i" ]
   	},
   	{
    	"name": "WSB.AC.default",
    	"delay": 120000
   	}
]
```
When a page is loaded AC scans the configurations, executes the first matching configuration, then quits processing.

For example,
    https://www.cnbc.com/2021/05/06/us-solar-workforce-fell-in-2020-but-industry-hopes-for-rebound-.html
 is a news story. It will match the  cnbc.com.202 pattern in WSB.AC.always and be saved. Processing for that page stops.

   https://www.cnbc.com/ is the home page for CNBC. It will match one of the domains in WSB.AC.ignore The page will be ignored. Processing stops.

   https://machinelearningmastery.com/weighted-average-ensemble-with-python/ is a page loaded doing research. It will match WSB.AC.default and be saved if i spend more than 2 minutes reading the page.

i estimate WSB.AC.always may slowly grow to a couple dozen patterns. i estimate WSB.AC.ignore will grow to more than 75 domains quickly.

Is there a chance i can get you to post your alternative configurations for the example above?


i do not understand helpers so i can not comment on general applicability.


Your comments RE RegEx compilers are theoretically true. But programs can have bugs. Short simple expressions get tested. Long complex expressions not so much.

And shorter expressions are more readable. Using your suggested pattern the RegExp for each domain would be about 25 characters long. If WSB.AC.ignore grows to 75 domains the RegExp for it would be about 1900 characters. Not sure many editors can handle that. And it is my understanding the JSON line continuation character may be different between implementations.

**Comment by danny0838** [comment] 2021-05-07 05:20
> Here is an example of a real use case defined as i propose. The only change is that i anonymized the WSB.AC.ignore domains.
> 
> ```
> [
>    	{
>     	"name": "WSB.AC.always",
> 	"allowDuplicate": 1,
>     	"pattern": [ "/.*us.econoday.com.byshoweventfull.*/i", "/.*cnbc.com.202.*/i" ],
>     	"delay": 2000
>    	},
>    	{
>     	"name": "WSB.AC.ignore",
> 		"ignore": 1,
>     	"pattern": [
> 			"/.*domain01.*/i", "/.*domain02.*/i", "/.*domain03.*/i",
> 			"/.*domain04.*/i", "/.*domain05.*/i", "/.*domain06.*/i",
> 			"/.*domain07.*/i", "/.*domain08.*/i", "/.*domain09.*/i",
> 			"/.*domain10.*/i", "/.*domain11.*/i", "/.*domain12.*/i",
> 			"/.*domain13.*/i", "/.*domain14.*/i", "/.*domain15.*/i",
> 			"/.*domain16.*/i", "/.*domain17.*/i", "/.*domain18.*/i",
> 			"/.*domain19.*/i", "/.*domain20.*/i", "/.*domain21.*/i",
> 			"/.*domain22.*/i", "/.*domain23.*/i", "/.*domain24.*/i",
> 			"/.*domain25.*/i", "/.*domain26.*/i" ]
>    	},
>    	{
>     	"name": "WSB.AC.default",
>     	"delay": 120000
>    	}
> ]
> ```

I don't see the point. `us.econoday.com` is totally independent with `domain01` etc., the first config will only work on pages under `us.econoday.com`, and you don't need the second config at all.

> When a page is loaded AC scans the configurations, executes the first matching configuration, then quits processing.
> 
> For example,
> https://www.cnbc.com/2021/05/06/us-solar-workforce-fell-in-2020-but-industry-hopes-for-rebound-.html
> is a news story. It will match the cnbc.com.202 pattern in WSB.AC.always and be saved. Processing for that page stops.
> 
> https://www.cnbc.com/ is the home page for CNBC. It will match one of the domains in WSB.AC.ignore The page will be ignored. Processing stops.

Why not just write a regexp that filters pages under `https://www.cnbc.com/2021/`? I still don't see a need of an extra config...

> https://machinelearningmastery.com/weighted-average-ensemble-with-python/ is a page loaded doing research. It will match WSB.AC.default and be saved if i spend more than 2 minutes reading the page.

So... what is your problem here? Just don't set allowduplicate, and a web page that has been captured by another rule won't be captured by this tule again.

> But programs can have bugs. Short simple expressions get tested. Long complex expressions not so much.

I don't think so. I never had a problem handling long regexps. If you really envounter such issue you should file a bug to its developers, not here.

> And shorter expressions are more readable. Using your suggested pattern the RegExp for each domain would be about 25 characters long. If WSB.AC.ignore grows to 75 domains the RegExp for it would be about 1900 characters. Not sure many editors can handle that. And it is my understanding the JSON line continuation character may be different between implementations.

You should write regexps that are specific and accurate enough, not lots of fuzzy regexps and complain that unwanted pages are included. If you keep doing so your condiguration will be poor on readibility and on performance.

**Comment by yellowslug** [comment] 2021-05-07 22:00
i'm sorry, but do not understand what you r saying. Please give me a sample config that will perform the operations listed in my example. i will look at it and reply.

thanks,

**Comment by danny0838** [comment] 2021-05-07 22:30
If you want to capture `https://www.cnbc.com/2021/05/06/us-solar-workforce-fell-in-2020-but-industry-hopes-for-rebound-.html` and siblings, and don't want `https://www.cnbc.com/`, you just need a config as simple as:

```
[
  {
    "pattern": "/^https://www\.cnbc\.com/2021/05/06//",
    "delay": 2000
  }
]
```

This will effectively include URLs under `https://www.cnbc.com/2021/05/06/` and won't include `https://www.cnbc.com/`.

If, instead, you want to include all articles like `https://www.cnbc.com/<year>/<month>/<date>/<title>` and don't want other entry/navigation pages like `https://www.cnbc.com/business/` or `https://www.cnbc.com/cybersecurity/`, you can write one like this:

```
[
  {
    "pattern": "/^https://www\.cnbc\.com/\d{4}/\d{2}/\d{2}//",
    "delay": 2000
  }
]
```

Therefore, the problem is simply all about writing a precise and specific RegExp.

If you want a precise demo for a more complicated case, you have to provide an accurate description about what you want to capture and what you don't want, and stop using "more readable" bad RegExps to confuse everything. No one will be able to help you if you failed to provide a precise and specific description about your intention.

**Comment by danny0838** [comment] 2021-05-09 00:59
> What i do not understand is how to ignore domain01 through domain26, and how to capture all other domains after 2 minutes.

This can be something like `"/^https?://(?!(?:domain1|domain2|domain3|...|domain26)/)/"`.

**Comment by yellowslug** [comment] 2021-05-09 20:41
i still do not understand. The pattern above is not a configuration. Even that snippet is complex and hard to understand. For example, not many people know that ?! stands for negative look ahead. Please post a complete equivalent to the following example. Then we can compare apples with apples.

regards,

```
[
   	{
    	"name": "WSB.AC.always",
	"allowDuplicate": 1,
    	"pattern": [ "/.*us.econoday.com.byshoweventfull.*/i", "/.*cnbc.com.202.*/i" ],
    	"delay": 2000
   	},
   	{
    	"name": "WSB.AC.ignore",
		"ignore": 1,
    	"pattern": [
			"/.*econoday.com.*/i", "/.*cnbc.com.*/i", "/.*domain03.*/i",
			"/.*domain04.*/i", "/.*domain05.*/i", "/.*domain06.*/i",
			"/.*domain07.*/i", "/.*domain08.*/i", "/.*domain09.*/i",
			"/.*domain10.*/i", "/.*domain11.*/i", "/.*domain12.*/i",
			"/.*domain13.*/i", "/.*domain14.*/i", "/.*domain15.*/i",
			"/.*domain16.*/i", "/.*domain17.*/i", "/.*domain18.*/i",
			"/.*domain19.*/i", "/.*domain20.*/i", "/.*domain21.*/i",
			"/.*domain22.*/i", "/.*domain23.*/i", "/.*domain24.*/i",
			"/.*domain25.*/i", "/.*domain26.*/i" ]
   	},
   	{
    	"name": "WSB.AC.default",
    	"delay": 120000
   	}
]
```

thanks,

**Comment by danny0838** [comment] 2021-05-09 23:20
> i still do not understand. The pattern above is not a configuration. Even that snippet is complex and hard to understand. For example, not many people know that ?! stands for negative look ahead. Please post a complete equivalent to the following example. Then we can compare apples with apples.
> 
> regards,
> 
> ```
> [
>    	{
>     	"name": "WSB.AC.always",
> 	"allowDuplicate": 1,
>     	"pattern": [ "/.*us.econoday.com.byshoweventfull.*/i", "/.*cnbc.com.202.*/i" ],
>     	"delay": 2000
>    	},
>    	{
>     	"name": "WSB.AC.ignore",
> 		"ignore": 1,
>     	"pattern": [
> 			"/.*econoday.com.*/i", "/.*cnbc.com.*/i", "/.*domain03.*/i",
> 			"/.*domain04.*/i", "/.*domain05.*/i", "/.*domain06.*/i",
> 			"/.*domain07.*/i", "/.*domain08.*/i", "/.*domain09.*/i",
> 			"/.*domain10.*/i", "/.*domain11.*/i", "/.*domain12.*/i",
> 			"/.*domain13.*/i", "/.*domain14.*/i", "/.*domain15.*/i",
> 			"/.*domain16.*/i", "/.*domain17.*/i", "/.*domain18.*/i",
> 			"/.*domain19.*/i", "/.*domain20.*/i", "/.*domain21.*/i",
> 			"/.*domain22.*/i", "/.*domain23.*/i", "/.*domain24.*/i",
> 			"/.*domain25.*/i", "/.*domain26.*/i" ]
>    	},
>    	{
>     	"name": "WSB.AC.default",
>     	"delay": 120000
>    	}
> ]
> ```

I will repeat the same saying (with strong added):

> If you want a precise demo for a more complicated case, you have to **provide an accurate description about what you want to capture and what you don't want, and stop using "more readable" bad RegExps to confuse everything**. No one will be able to help you if you failed to provide a precise and specific description about your intention.

Regular expression is a very powerful tool that is used in lots of programming languages and softwares. There are probably millions of resources everywhere. You can Google "regular expression" for a tutorial if you are not familiar about it. For example, [this video](https://www.youtube.com/watch?v=sXQxhojSdZM) (2:21), [this video](https://www.youtube.com/watch?v=sa-TUpSx1JA) (37:54), or [this website](https://refrf.shreyasminocha.me/) are likely something good to start with.

Just note that since you have to embed a RegExp in a JSON string, you have to escape it, which is usually by replacing `\` with `\\`. For example, a RegExp pattern `/^https://www\.cnbc\.com/\d{4}/\d{2}/\d{2}//` or `^https://www\.cnbc\.com/\d{4}/\d{2}/\d{2}/` (with no flag/modifier) will be `"/^https://www\\.cnbc\\.com/\\d{4}/\\d{2}/\\d{2}//"` in JSON.

**Comment by yellowslug** [comment] 2021-05-22 12:48
My suggestions are not about regular expressions. They are about providing an interface the general public can use. imo, we've spent more time on this than it would take to make the changes. imo, if u post an apples to apples configuration that matches mine it will be apparent how difficult current configuration is.

Something easily understood, debugged and maintained will make webscrapbook invaluable to many many more people. What will it take to convince you to do this?

**Comment by danny0838** [comment] 2021-05-22 13:30
We have been implemented lots of enhancement requests so far, but only when there's a true demand and a good design has been come out. Regretfully, none of them is seen in this issue.

RegExp is already the easiest and most performant way to deal with the cases you have raised so far. It is also a universal technique and can be used in many other applications, such as OpenOffice, Notepad++, XnView, shell script, etc., once well learned, and take some time to learn it won't be a waste. Implementing another wildcard syntax or JSON scheme to deal with such cases seems to just make things more complicated, less universal, and less performant.

**Comment by yellowslug** [comment] 2021-05-27 02:43
if anyone else is up to this task please contact me off list. trhodes3 yahoo

**Closed** 2021-05-29 04:51 UTC
Labels: not a bug

**Comment by JuchiaLu** [comment] 2023-03-03 06:59
感谢作者，这是我尝试很多项目之后，才找到的一个很满意的项目，但我想重新打开这个 issues。



原来的匹配方式，每个 pattern 是独立的“肯定匹配”，对于明确知道要自动保存哪些网址时比较友好，

但对于不明确知道什么网址需要自动保存、只想排除掉一些不需要保存的网址时不太友好，原因如下：

1. 人们更加喜欢写肯定匹配的 pattern，而不是否定匹配的。
2. 当有多个不想自动保存的网址时，需要写一个复杂的 pattern，想要再次修改时是一个很大的挑战。
3. 即使写了一个要排除的复杂 pattern，但它想要排除的网址可能被别的 pattern 匹配上，导致意外的捕获。
4. 关于性能，多个小的 pattern 可能确实要比单个大的 pattern 更耗性能，但对于浏览器来说影响不大。



举个例子，这是 autoCaptureConfig：

```json
[
    {
        "name": "exclude baidu",
        "pattern": "/^https?://www\\.baidu\\.com.*//i",
        "exclude": true
    },
    {
        "name": "exclude google",
        "pattern": "/^https?://www\\.google\\.com.*//i",
        "exclude": true
    },
    {
        "name": "exclude bing",
        "pattern": "/^https?://www\\.bing\\.com.*//i",
        "exclude": true
    },

    // ... exclude

    {
        "name": "Auto capture all",
        "delay": 180000,
        "allowDuplicate": true
    }  
]
```

为了更好的表达我的意图，我直接修改 src\capturer\background.js 中的源代码来说明：

```JavaScript
async function autoCaptureTab(tabInfo) {

    ...

    for (let i = 0, I = autoCaptureConfigs.length; i < I; ++i) {
        const config = autoCaptureConfigs[i];

        ...

        // check pattern
        if (config.pattern) {
            config.pattern.lastIndex = 0;
            let test = config.pattern.test(tabInfo.url)
            if(test && config.exclude) {
                break;
            }
            if (!test) {
                continue;
            }
        }

        ... 

        // test && !config.exclude 的将会被保存
        invokeCapture(tabInfo, config, false);

        break;  
    }
}
```
每个 pattern 独立开，不用合并成一个大的 pattern 后，当要添加、删除或修体某个 pattern 时，不怕影响到别的 pattern。


再次感谢。

**Comment by danny0838** [comment] 2023-03-03 07:37
@JuchiaLu 我們不會考慮這種做法。原來設計是各個 rule (主陣列中含有 pattern 等值的項目) 彼此獨立，你提案的做法會導致各 rule 可能互相干擾，造成使用上的混亂與麻煩，同時也無法應付稍微複雜一點的需求，例如「Facebook 網站頁面 delay 30s 自動下載；非 Baidu, Google, Facebook 的網站 delay 180s 自動下載」。

**Comment by JuchiaLu** [comment] 2023-03-03 07:52
@danny0838 这种做法，rule 是具有优先级的，优先级高的放在数组前，优先级低的放在末尾，人们可以根据需求安排 rule 的顺序，这提供了很大的灵活性，比如：「Facebook, Baidu 網站頁面 delay 30s 自動下載；非 Baidu, Google, Facebook 的網站頁面 delay 180s 自動下載」的放在前面，要排除的 rule 放在后面，当然这种改动对于老用户可能一时难以适应，不会实现也表示理解，再次感谢。
